# command line: main.py --config config/uav-csv1/default.yaml --work-dir work_dir/uav1/skmixf_bonemotion --device 2 3

# python main.py --config /media/sdd/robot/ICMEW2024-Track10/Model_inference/Mix_Former/config/mixformer_V1_BM.yaml --device 0 1 

# python main.py --config ./config/mixformer_V1_BM.yaml --phase test --save-score True --weights /media/sdd/robot/ICMEW2024-Track10/Model_inference/Mix_Former/output/skmixf__V1_BM/runs-64-2048.pt --device 0 1 2 3
# /media/sdd/robot/ICMEW2024-Track10/Model_inference/Mix_Former/output/skmixf__V1_BM/runs-64-2048.pt

#33.45
# /media/sdd/robot/ICMEW2024-Track10/Model_inference/Mix_Former/output/skmixf__V1_BM_enhance/runs-59-3776.pt
# python main.py --config ./config/mixformer_V1_BM.yaml --phase test --save-score True --weights /media/sdd/robot/ICMEW2024-Track10/Model_inference/Mix_Former/output/skmixf__V1_BM_enhance/runs-59-3776.pt --device 0 1 2 3

base_lr: 0.3
batch_size: 256
config: config/uav-csv1/default.yaml
device:
- 2
- 3
eval_interval: 5
feeder: feeders.feeder_uav.Feeder
ignore_weights: []
log_interval: 100
model: model.ske_mixf.Model
model_args:
  graph: graph.uav.Graph
  graph_args:
    labeling_mode: spatial
  num_class: 155
  num_person: 2
  num_point: 17
model_saved_name: ''
nesterov: true
num_epoch: 70
#70轮没有手里拿，还是本身效果很差？？
num_worker: 32
optimizer: SGD
phase: train
print_log: true
save_epoch: 30
save_interval: 1
save_score: True
seed: 1
show_topk:
- 1
- 5
start_epoch: 0
step:
- 50
test_batch_size: 256
test_feeder_args:
  bone: true
  # data_path: /media/sdd/robot/guosai-data/test/test_bone_motion.npz
  data_path: /media/sdd/robot/guosai-data/3497/3497_bone_motion.npz
  debug: false
  p_interval:
  - 0.95
  split: test
  vel: true
  window_size: 64
train_feeder_args:
  bone: true
  # data_path: /media/sdd/robot/guosai-data/test/test_bone_motion.npz
  data_path: /media/sdd/robot/guosai-data/3497/3497_bone_motion.npz
  debug: false
  normalization: false
  p_interval:
  - 0.5
  - 1
  random_choose: false
  random_move: True
  random_rot: false
  random_shift: True
  split: train
  vel: true
  window_size: 64
warm_up_epoch: 5
weight_decay: 0.0005
weights: null

# work_dir: ./res_phase2/skmixf__V1_BM_enhance  
work_dir: ./res_phase2_3497/skmixf__V1_BM_enhance 
