python main.py --config /media/sdd/robot/ICMEW2024-Track10/Model_inference/Mix_Former/config/phase2/config4testb/mixformer_V1_J_test.yaml --phase test --save-score True --weights /media/sdd/robot/ICMEW2024-Track10/Model_inference/Mix_Former/output_phase2/skmixf__V1_J_enhance/runs-54-3510.pt --device 1 2 3
python main.py --config /media/sdd/robot/ICMEW2024-Track10/Model_inference/Mix_Former/config/phase2/config4testb/mixformer_V1_B_test.yaml --phase test --save-score True --weights /media/sdd/robot/ICMEW2024-Track10/Model_inference/Mix_Former/output_phase2/skmixf__V1_B_enhance/runs-56-3640.pt --device 1 2 3
python main.py --config /media/sdd/robot/ICMEW2024-Track10/Model_inference/Mix_Former/config/phase2/config4testb/mixformer_V1_JM_test.yaml --phase test --save-score True --weights /media/sdd/robot/ICMEW2024-Track10/Model_inference/Mix_Former/output_phase2/skmixf__V1_JM_enhance/runs-60-3900.pt --device 1 2 3
python main.py --config /media/sdd/robot/ICMEW2024-Track10/Model_inference/Mix_Former/config/phase2/config4testb/mixformer_V1_BM_test.yaml --phase test --save-score True --weights /media/sdd/robot/ICMEW2024-Track10/Model_inference/Mix_Former/output_phase2/skmixf__V1_BM_enhance/runs-62-4030.pt --device 1 2 3
python main.py --config /media/sdd/robot/ICMEW2024-Track10/Model_inference/Mix_Former/config/phase2/config4testb/mixformer_V1_k2_test.yaml --phase test --save-score True --weights /media/sdd/robot/ICMEW2024-Track10/Model_inference/Mix_Former/output_phase2/skmixf__V1_k2_enhance/runs-62-4030.pt --device 1 2 3
python main.py --config /media/sdd/robot/ICMEW2024-Track10/Model_inference/Mix_Former/config/phase2/config4testb/mixformer_V1_k2M_test.yaml --phase test --save-score True --weights /media/sdd/robot/ICMEW2024-Track10/Model_inference/Mix_Former/output_phase2/skmixf__V1_k2M_enhance/runs-53-3445.pt --device 1 2 3
python main.py --config /media/sdd/robot/ICMEW2024-Track10/Model_inference/Mix_Former/config/phase2/config4testb/mixformer_V1_J_test_none.yaml --phase test --save-score True --weights /media/sdd/robot/ICMEW2024-Track10/Model_inference/Mix_Former/output_phase2_v2/skmixf__V1_J_enhance_none/runs-57-3705.pt --device 1 
python main.py --config /media/sdd/robot/ICMEW2024-Track10/Model_inference/Mix_Former/config/phase2/config4testb/mixformer_V1_J_test_rot.yaml --phase test --save-score True --weights /media/sdd/robot/ICMEW2024-Track10/Model_inference/Mix_Former/output_phase2_v2/skmixf__V1_J_enhance_rot/runs-54-3510.pt --device 1
python main.py --config /media/sdd/robot/ICMEW2024-Track10/Model_inference/Mix_Former/config/phase2/config4testb/mixformer_V1_J_test_move.yaml --phase test --save-score True --weights /media/sdd/robot/ICMEW2024-Track10/Model_inference/Mix_Former/output_phase2_v2/skmixf__V1_J_enhance_move/runs-56-3640.pt --device 1
python main.py --config /media/sdd/robot/ICMEW2024-Track10/Model_inference/Mix_Former/config/phase2/config4testb/mixformer_V1_J_test_shift.yaml --phase test --save-score True --weights /media/sdd/robot/ICMEW2024-Track10/Model_inference/Mix_Former/output_phase2_v2/skmixf__V1_J_enhance_shift/runs-59-3835.pt --device 1
python main.py --config /media/sdd/robot/ICMEW2024-Track10/Model_inference/Mix_Former/config/phase2/config4testb/mixformer_V1_k2_test_move.yaml --phase test --save-score True --weights /media/sdd/robot/ICMEW2024-Track10/Model_inference/Mix_Former/output_phase2_v2/skmixf__V1_k2_enhance_move/runs-54-7020.pt --device 1
python main.py --config /media/sdd/robot/ICMEW2024-Track10/Model_inference/Mix_Former/config/phase2/config4testb/mixformer_V1_k2_test_rot.yaml --phase test --save-score True --weights /media/sdd/robot/ICMEW2024-Track10/Model_inference/Mix_Former/output_phase2_v2/skmixf__V1_k2_enhance_rot/runs-55-3575.pt --device 1
python main.py --config /media/sdd/robot/ICMEW2024-Track10/Model_inference/Mix_Former/config/phase2/config4testb/mixformer_V1_k2_test_shift.yaml --phase test --save-score True --weights /media/sdd/robot/ICMEW2024-Track10/Model_inference/Mix_Former/output_phase2_v2/skmixf__V1_k2_enhance_shift/runs-57-3705.pt --device 1
python main.py --config /media/sdd/robot/ICMEW2024-Track10/Model_inference/Mix_Former/config/phase2/config4testb/mixformer_V1_k2_test_none.yaml --phase test --save-score True --weights /media/sdd/robot/ICMEW2024-Track10/Model_inference/Mix_Former/output_phase2_v2/skmixf__V1_k2_enhance_none/runs-59-7670.pt --device 1 
python main.py --config /media/sdd/robot/ICMEW2024-Track10/Model_inference/Mix_Former/config/phase2/config4testb/mixformer_V1_B_test_none.yaml --phase test --save-score True --weights /media/sdd/robot/ICMEW2024-Track10/Model_inference/Mix_Former/output_phase2_v2/skmixf__V1_B_enhance_none/runs-55-3575.pt --device 1 
python main.py --config /media/sdd/robot/ICMEW2024-Track10/Model_inference/Mix_Former/config/phase2/config4testb/mixformer_V1_B_test_shift.yaml --phase test --save-score True --weights /media/sdd/robot/ICMEW2024-Track10/Model_inference/Mix_Former/output_phase2_v2/skmixf__V1_B_enhance_shift/runs-57-7410.pt --device 1
python main.py --config /media/sdd/robot/ICMEW2024-Track10/Model_inference/Mix_Former/config/phase2/config4testb/mixformer_V1_B_test_rot.yaml --phase test --save-score True --weights /media/sdd/robot/ICMEW2024-Track10/Model_inference/Mix_Former/output_phase2_v2/skmixf__V1_B_enhance_rot/runs-57-7410.pt --device 1
python main.py --config /media/sdd/robot/ICMEW2024-Track10/Model_inference/Mix_Former/config/phase2/config4testb/mixformer_V1_B_test_move.yaml --phase test --save-score True --weights /media/sdd/robot/ICMEW2024-Track10/Model_inference/Mix_Former/output_phase2_v2/skmixf__V1_B_enhance_move/runs-62-4030.pt --device 1
python main.py --config /media/sdd/robot/ICMEW2024-Track10/Model_inference/Mix_Former/config/phase2/config4testb/mixformer_V1_k2M_test_move.yaml --phase test --save-score True --weights /media/sdd/robot/ICMEW2024-Track10/Model_inference/Mix_Former/output_phase2_v2/skmixf__V1_k2M_enhance_move/runs-54-7020.pt --device 1
python main.py --config /media/sdd/robot/ICMEW2024-Track10/Model_inference/Mix_Former/config/phase2/config4testb/mixformer_V1_k2M_test_shift.yaml --phase test --save-score True --weights /media/sdd/robot/ICMEW2024-Track10/Model_inference/Mix_Former/output_phase2_v2/skmixf__V1_k2M_enhance_shift/runs-53-6890.pt --device 1 
python main.py --config /media/sdd/robot/ICMEW2024-Track10/Model_inference/Mix_Former/config/phase2/config4testb/mixformer_V1_k2M_test_rot.yaml --phase test --save-score True --weights /media/sdd/robot/ICMEW2024-Track10/Model_inference/Mix_Former/output_phase2_v2/skmixf__V1_k2M_enhance_rot/runs-54-7020.pt --device 1  
python main.py --config /media/sdd/robot/ICMEW2024-Track10/Model_inference/Mix_Former/config/phase2/config4testb/mixformer_V1_k2M_test_none.yaml --phase test --save-score True --weights /media/sdd/robot/ICMEW2024-Track10/Model_inference/Mix_Former/output_phase2_v2/skmixf__V1_k2M_enhance_none/runs-54-7020.pt --device 1



