# command line: main.py --config /media/sdd/robot/ICMEW2024-Track10/Model_inference/Mix_Former/config/phase2/config/mixformer_V1_JM.yaml --device 1 2

base_lr: 0.3
batch_size: 256
config: /media/sdd/robot/ICMEW2024-Track10/Model_inference/Mix_Former/config/phase2/config/mixformer_V1_JM.yaml
device:
- 1
- 2
eval_interval: 5
feeder: feeders.feeder_uav.Feeder
ignore_weights: []
log_interval: 100
model: model.ske_mixf.Model
model_args:
  graph: graph.uav.Graph
  graph_args:
    labeling_mode: spatial
  num_class: 155
  num_person: 2
  num_point: 17
model_saved_name: ''
nesterov: true
num_epoch: 70
num_worker: 32
optimizer: SGD
phase: train
print_log: true
save_epoch: 30
save_interval: 1
save_score: true
seed: 1
show_topk:
- 1
- 5
start_epoch: 0
step:
- 50
test_batch_size: 256
test_feeder_args:
  bone: false
  data_path: /media/sdd/robot/guosai-data/train/train_joint_motion.npz
  debug: false
  p_interval:
  - 0.95
  split: test
  vel: true
  window_size: 64
train_feeder_args:
  bone: false
  data_path: /media/sdd/robot/guosai-data/train/train_joint_motion.npz
  debug: false
  normalization: false
  p_interval:
  - 0.5
  - 1
  random_choose: false
  random_move: true
  random_rot: false
  random_shift: true
  split: train
  vel: true
  window_size: 64
warm_up_epoch: 5
weight_decay: 0.0005
weights: null
work_dir: ./output_phase2/skmixf__V1_JM_enhance
